[extension]
name = "MeowFace"
translation-key = "MEOWFACE_EXTENSION_NAME"

[[resources]]
name = "Tracker"
tags = ["tracker"]
entrypoint = "meowface.gd"
gui = "gui.gd"
translation-key = "MEOWFACE_EXTENSION_NAME"
